#!/usr/bin/env node
/**
 * Embeds the HA card JS (video-player + card + gallery) into TypeScript files as string constants.
 * Run before main webpack build.
 *
 * Outputs:
 *   src/ha-card-embedded.ts      - VideoPlayer + Gallery + DailyBriefCard concatenated (HA card bundle)
 *   src/video-player-embedded.ts - VideoPlayer only (for web UI inline embed)
 *   src/gallery-embedded.ts      - Gallery only (for web UI inline embed)
 */
const fs = require('fs');
const path = require('path');

const videoPlayerPath = path.join(__dirname, '..', 'ha-card', 'video-player.js');
const haCardPath = path.join(__dirname, '..', 'ha-card', 'daily-brief-card.js');
const galleryPath = path.join(__dirname, '..', 'ha-card', 'gallery.js');
const haEmbedOutputPath = path.join(__dirname, '..', 'src', 'ha-card-embedded.ts');
const vpEmbedOutputPath = path.join(__dirname, '..', 'src', 'video-player-embedded.ts');
const galleryEmbedOutputPath = path.join(__dirname, '..', 'src', 'gallery-embedded.ts');

if (!fs.existsSync(videoPlayerPath)) {
  console.error('Missing source: ha-card/video-player.js');
  process.exit(1);
}
if (!fs.existsSync(haCardPath)) {
  console.error('Missing source: ha-card/daily-brief-card.js');
  process.exit(1);
}
if (!fs.existsSync(galleryPath)) {
  console.error('Missing source: ha-card/gallery.js');
  process.exit(1);
}

const videoPlayerJs = fs.readFileSync(videoPlayerPath, 'utf8');
const haCardJs = fs.readFileSync(haCardPath, 'utf8');
const galleryJs = fs.readFileSync(galleryPath, 'utf8');

// HA card bundle: VideoPlayer first, then Gallery, then DailyBriefCard (all in global scope)
const bundleContent = videoPlayerJs + '\n' + galleryJs + '\n' + haCardJs;

const haEmbedTs = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/embed-ha-card.js
// Source: ha-card/video-player.js + ha-card/gallery.js + ha-card/daily-brief-card.js

export const HA_CARD_JS = ${JSON.stringify(bundleContent)};
`;

// VideoPlayer only (for web UI inline embed)
const vpEmbedTs = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/embed-ha-card.js
// Source: ha-card/video-player.js

export const VIDEO_PLAYER_JS = ${JSON.stringify(videoPlayerJs)};
`;

// Gallery only (for web UI inline embed)
const galleryEmbedTs = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/embed-ha-card.js
// Source: ha-card/gallery.js

export const GALLERY_JS = ${JSON.stringify(galleryJs)};
`;

fs.writeFileSync(haEmbedOutputPath, haEmbedTs);
fs.writeFileSync(vpEmbedOutputPath, vpEmbedTs);
fs.writeFileSync(galleryEmbedOutputPath, galleryEmbedTs);
console.log('Embedded HA card bundle into src/ha-card-embedded.ts');
console.log('Embedded VideoPlayer into src/video-player-embedded.ts');
console.log('Embedded Gallery into src/gallery-embedded.ts');
